server:
  port: 8009
spring:
  application:
    name: cloud_consumer_hystrix_dashboard

    # sleuth 部分添加
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/SpringCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jin1997c#

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 192.168.1.103

feign:
  hystrix:
    enabled: true
