#该文件在配置中心对应的文件名称:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}=nacos-payment-providerdev.yaml

server:
  port: 9001

spring:
  #  profiles:
  #    active: dev

  application:
    name: nacos-payment-provider
  cloud:
    nacos:

      discovery:
        #        配置nacos地址
        server-addr: 192.168.1.103:80

#      config:
#        password: nacos
#        username: nacos
#        server-addr: localhost:8848
#        file-extension: yaml
#        group: dev_group
#        namespace: 7c9b6687-c334-4a29-925c-f9f1bd9a6453

service-uris:
  consumerOrderUrl: http://nacos-consumer-order

#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
