#该文件在配置中心对应的文件名称:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}=nacos-payment-providerdev.yaml

server:
  port: 9003

spring:

  application:
    name: cloud-seata-pay-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attest?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jin1997c#

  cloud:
    nacos:
      discovery:
        group: SEATA_GROUP
        server-addr: localhost:80

      config:
        group: SEATA_GROUP

    alibaba:
      seata:
        cloud-seata-pay-service-group: default

#seata:
#  enabled: true
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:80
#      dataId: "seataServer.properties"
#      group: "DEFAULT_GROUP"
#      namespace: ""
#      username: "nacos"
#      password: "nacos"

#  tx-service-group: myGroup  #事务组名称,需要和配置中心的service.vgroupMapping保持一致
#
#  service:
#    vgroup-mapping:
#      myGroup: hzTransaction  #key是事务组名称,value要和机房名称一致
#    grouplist:
#      default: 127.0.0.1:8091

#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io:
      seata: debug
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

mybatis:
  type-aliases-package: com.mashibing.seata.pojo.*
  mapper-locations: classpath:/mapper/*.xml
