#该文件在配置中心对应的文件名称:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}=nacos-payment-providerdev.yaml

server:
  port: 9003

spring:

  application:
    name: pay-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attest?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jin1997c#

  cloud:
    nacos:
      discovery:
        group: SEATA_GROUP
        server-addr: 192.168.2.222:80

      config:
        server-addr: 192.168.2.222:80
        group: SEATA_GROUP

#    alibaba:
#      seata:
#        tx-service-group: pay-service-fescar-service-group
  # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应

# seata 配置
seata:
  tx-service-group: pay-service-fescar-service-group
  service:
    # 事务组对应的集群民称
    vgroup-mapping:
      pay-service-fescar-service-group: default

  enable-auto-data-source-proxy: false

#  enabled: true
#
#  groupList:
#    seata-server: 192.168.2.222:8091
#
#  config:
#    nacos:
#      data-id: seataServer.properties
#      server-addr: 192.168.2.222:80
#  registry:
#    nacos:
#      server-addr: 192.168.2.222:80

#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: com.mashibing.pojo.*
  mapper-locations: classpath:/mapper/*.xml
