#该文件在配置中心对应的文件名称:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}=nacos-payment-providerdev.yaml

server:
  port: 9004

spring:

  application:
    name: cloud-seata

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attest?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jin1997c#

  cloud:
    nacos:
      discovery:
        group: SEATA_GROUP
        server-addr: 192.168.1.106:80

      config:
        server-addr: 192.168.1.106:80
        group: SEATA_GROUP

#    alibaba:
#      seata:
#        tx-service-group: seataCluster

# seata 配置
seata:
#   使用哪个事务组
#  tx-service-group: my_tx_service_group
  service:
    # 事务组对应的集群民称
    vgroup-mapping:
      cloud-seata-seata-service-group: default

    # seata-server的地址
#    grouplist:
#      seata-server: 127.0.0.1:8091

  enabled: true

  config:
    nacos:
      data-id: seataServer.properties
  registry:
    nacos:
      server-addr: 192.168.1.106:80

#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io:
      seata: debug
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

mybatis:
  type-aliases-package: com.mashibing.seata.pojo.*
  mapper-locations: classpath:/mapper/*.xml
